<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

/**
 * native:install mirrors the vendor stub over nativephp/android (robocopy
 * /MIR), which silently wipes every hand-applied Kotlin fix — and the
 * nativephp/ tree is gitignored, so those fixes live nowhere else. This
 * command re-applies the tracked copies from native-patches/ and must run
 * after every native:install and before every native:package.
 */
class NativePatch extends Command
{
    protected $signature = 'native:patch';

    protected $description = 'Re-apply tracked native Kotlin patches (native-patches/) to the nativephp/android build';

    protected array $files = [
        'app/src/main/java/com/nativephp/mobile/network/WebViewManager.kt',
        'app/src/main/java/com/nativephp/mobile/bridge/PHPBridge.kt',
        'app/src/main/java/com/nativephp/mobile/bridge/BridgeFunctionRegistration.kt',
        'app/src/main/java/com/nativephp/mobile/bridge/functions/PrintFunctions.kt',
        // Files.* — the native document picker that feeds a file the shop
        // already owns (backup_*.json) back to PHP as base64, since the WebView
        // cannot upload one.
        'app/src/main/java/com/nativephp/mobile/bridge/functions/FilePickerFunctions.kt',
        // Manifest + FileProvider paths: the storage permission for saving
        // printed documents and the extra shareable paths live here, and both
        // files are regenerated by native:install.
        'app/src/main/AndroidManifest.xml',
        'app/src/main/res/xml/file_paths.xml',
        // Status bar hidden (clock/battery/signal) — hand edit in MainActivity.
        'app/src/main/java/com/nativephp/mobile/ui/MainActivity.kt',
        // Adaptive launcher icon background must match the MGS brand green
        // (stock stub ships white, which peeks out behind the icon mask).
        'app/src/main/res/drawable/ic_launcher_background.xml',
        // Splash screen resources the patched MainActivity.kt references:
        // the overlay background color and the wallet logo glyph.
        'app/src/main/res/values/colors.xml',
        'app/src/main/res/drawable/ic_splash_logo.xml',
    ];

    public function handle(): int
    {
        $targetBase = base_path('nativephp/android');

        if (! is_dir($targetBase)) {
            $this->error('nativephp/android not found — run native:install first.');

            return self::FAILURE;
        }

        foreach ($this->files as $relative) {
            $from = base_path('native-patches/'.$relative);
            $to = $targetBase.'/'.$relative;

            if (! is_file($from)) {
                $this->error("Patch source missing: {$from}");

                return self::FAILURE;
            }

            if (! is_dir(dirname($to))) {
                mkdir(dirname($to), 0777, true);
            }

            copy($from, $to);
            $this->line("  ✓ {$relative}");
        }

        $this->info('Native patches applied ('.count($this->files).' files).');

        return self::SUCCESS;
    }
}
